In [1]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
adult = fetch_ucirepo(id=2) 
  
# data (as pandas dataframes) 
X = adult.data.features 
y = adult.data.targets 
  
# metadata 
print(adult.metadata) 
  
# variable information 
print(adult.variables) 


{'uci_id': 2, 'name': 'Adult', 'repository_url': 'https://archive.ics.uci.edu/dataset/2/adult', 'data_url': 'https://archive.ics.uci.edu/static/public/2/data.csv', 'abstract': 'Predict whether income exceeds $50K/yr based on census data. Also known as "Census Income" dataset. ', 'area': 'Social Science', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 48842, 'num_features': 14, 'feature_types': ['Categorical', 'Integer'], 'demographics': ['Age', 'Income', 'Education Level', 'Other', 'Race', 'Sex'], 'target_col': ['income'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 1996, 'last_updated': 'Mon Aug 07 2023', 'dataset_doi': '10.24432/C5XW20', 'creators': ['Barry Becker', 'Ronny Kohavi'], 'intro_paper': None, 'additional_info': {'summary': 'Extraction was done by Barry Becker from the 1994 Census database.  A set of reasonably clean records was extracted using the following conditions: ((AAG

In [8]:
import pandas as pd
import numpy as np
import seaborn as sns
df = pd.read_excel(r'C:\Users\tanis\OneDrive\Desktop\adult.xls')
df

age          workclass  fnlwgt    education  education-num  \
0       39          State-gov   77516    Bachelors             13   
1       50   Self-emp-not-inc   83311    Bachelors             13   
2       38            Private  215646      HS-grad              9   
3       53            Private  234721         11th              7   
4       28            Private  338409    Bachelors             13   
...    ...                ...     ...          ...            ...   
32556   27            Private  257302   Assoc-acdm             12   
32557   40            Private  154374      HS-grad              9   
32558   58            Private  151910      HS-grad              9   
32559   22            Private  201490      HS-grad              9   
32560   52       Self-emp-inc  287927      HS-grad              9   

            marital-status          occupation    relationship    race  \
0            Never-married        Adm-clerical   Not-in-family   White   
1       Married-civ-spouse     Exec-managerial         Husband   White   
2                 Divorced   Handlers-cleaners   Not-in-family   White   
3       Married-civ-spouse   Handlers-cleaners         Husband   Black   
4       Married-civ-spouse      Prof-specialty            Wife   Black   
...                    ...                 ...             ...     ...   
32556   Married-civ-spouse        Tech-support            Wife   White   
32557   Married-civ-spouse   Machine-op-inspct         Husband   White   
32558              Widowed        Adm-clerical       Unmarried   White   
32559        Never-married        Adm-clerical       Own-child   White   
32560   Married-civ-spouse     Exec-managerial            Wife   White   

           sex  capital-gain  capital-loss  hours-per-week  native-country  \
0         Male          2174             0              40   United-States   
1         Male             0             0              13   United-States   
2         Male             0             0              40   United-States   
3         Male             0             0              40   United-States   
4       Female             0             0              40            Cuba   
...        ...           ...           ...             ...             ...   
32556   Female             0             0              38   United-States   
32557     Male             0             0              40   United-States   
32558   Female             0             0              40   United-States   
32559     Male             0             0              20   United-States   
32560   Female         15024             0              40   United-States   

       income  
0       <=50K  
1       <=50K  
2       <=50K  
3       <=50K  
4       <=50K  
...       ...  
32556   <=50K  
32557    >50K  
32558   <=50K  
32559   <=50K  
32560    >50K  

[32561 rows x 15 columns]

In [9]:
df.shape

(32561, 15)

In [10]:
df.nunique()

age                  73
workclass             9
fnlwgt            21648
education            16
education-num        16
marital-status        7
occupation           15
relationship          6
race                  5
sex                   2
capital-gain        119
capital-loss         92
hours-per-week       94
native-country       42
income                2
dtype: int64

In [28]:
df['workclass']=df['workclass'].astype('category')
df['workclass']=df['workclass'].cat.codes
df['education']=df['education'].astype('category')
df['education']=df['education'].cat.codes
df['marital-status']=df['marital-status'].astype('category')
df['marital-status']=df['marital-status'].cat.codes
df['occupation']=df['occupation'].astype('category')
df['occupation']=df['occupation'].cat.codes
df['relationship']=df['relationship'].astype('category')
df['relationship']=df['relationship'].cat.codes
df['sex']=df['sex'].astype('category')
df['sex']=df['sex'].cat.codes
df['race']=df['race'].astype('category')
df['race']=df['race'].cat.codes
df['native-country']=df['native-country'].astype('category')
df['native-country']=df['native-country'].cat.codes
df['income']=df['income'].astype('category')
df['income']=df['income'].cat.codes
df

age  workclass  fnlwgt  education  education-num  marital-status  \
0       39          7   77516          9             13               4   
1       50          6   83311          9             13               2   
2       38          4  215646         11              9               0   
3       53          4  234721          1              7               2   
4       28          4  338409          9             13               2   
...    ...        ...     ...        ...            ...             ...   
32556   27          4  257302          7             12               2   
32557   40          4  154374         11              9               2   
32558   58          4  151910         11              9               6   
32559   22          4  201490         11              9               4   
32560   52          5  287927         11              9               2   

       occupation  relationship  race  sex  capital-gain  capital-loss  \
0               1             1     4    1          2174             0   
1               4             0     4    1             0             0   
2               6             1     4    1             0             0   
3               6             0     2    1             0             0   
4              10             5     2    0             0             0   
...           ...           ...   ...  ...           ...           ...   
32556          13             5     4    0             0             0   
32557           7             0     4    1             0             0   
32558           1             4     4    0             0             0   
32559           1             3     4    1             0             0   
32560           4             5     4    0         15024             0   

       hours-per-week  native-country  income  
0                  40              39       0  
1                  13              39       0  
2                  40              39       0  
3                  40              39       0  
4                  40               5       0  
...               ...             ...     ...  
32556              38              39       0  
32557              40              39       1  
32558              40              39       0  
32559              20              39       0  
32560              40              39       1  

[32561 rows x 15 columns]

In [29]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
income            0
dtype: int64

In [30]:
X= df.drop(columns="income")
X

age  workclass  fnlwgt  education  education-num  marital-status  \
0       39          7   77516          9             13               4   
1       50          6   83311          9             13               2   
2       38          4  215646         11              9               0   
3       53          4  234721          1              7               2   
4       28          4  338409          9             13               2   
...    ...        ...     ...        ...            ...             ...   
32556   27          4  257302          7             12               2   
32557   40          4  154374         11              9               2   
32558   58          4  151910         11              9               6   
32559   22          4  201490         11              9               4   
32560   52          5  287927         11              9               2   

       occupation  relationship  race  sex  capital-gain  capital-loss  \
0               1             1     4    1          2174             0   
1               4             0     4    1             0             0   
2               6             1     4    1             0             0   
3               6             0     2    1             0             0   
4              10             5     2    0             0             0   
...           ...           ...   ...  ...           ...           ...   
32556          13             5     4    0             0             0   
32557           7             0     4    1             0             0   
32558           1             4     4    0             0             0   
32559           1             3     4    1             0             0   
32560           4             5     4    0         15024             0   

       hours-per-week  native-country  
0                  40              39  
1                  13              39  
2                  40              39  
3                  40              39  
4                  40               5  
...               ...             ...  
32556              38              39  
32557              40              39  
32558              40              39  
32559              20              39  
32560              40              39  

[32561 rows x 14 columns]

In [31]:
y=df["income"]

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=23)
X_train

age  workclass  fnlwgt  education  education-num  marital-status  \
5558    38          4  114079         11              9               2   
12196   32          4  151053         15             10               4   
11516   18          0  179484          2              8               4   
26207   40          4  210648          9             13               2   
28126   34          4  212781          9             13               2   
...    ...        ...     ...        ...            ...             ...   
11190   18          4  130652         15             10               4   
26569   27          4  333296          9             13               4   
9256    36          4  312206         11              9               2   
29414   33          1   94193         11              9               0   
8787    20          4   34590         15             10               4   

       occupation  relationship  race  sex  capital-gain  capital-loss  \
5558           12             0     4    1             0             0   
12196           3             4     4    1             0             0   
11516           0             3     3    1             0             0   
26207          10             0     4    1             0             0   
28126           4             0     4    1             0             0   
...           ...           ...   ...  ...           ...           ...   
11190           1             3     4    0             0             0   
26569           8             1     4    1             0             0   
9256            7             0     4    1             0             0   
29414           1             4     4    0             0             0   
8787            5             3     4    1             0             0   

       hours-per-week  native-country  
5558               44              39  
12196              40              39  
11516              40              39  
26207              44              39  
28126              40              39  
...               ...             ...  
11190              25              39  
26569              30               0  
9256               40              39  
29414              40              39  
8787               60              39  

[22792 rows x 14 columns]

In [33]:
X_test

age  workclass  fnlwgt  education  education-num  marital-status  \
22466   40          4  225193         11              9               2   
1826    22          6  202920         11              9               4   
6377    46          4  364913          1              7               2   
19643   50          4  204447         12             14               2   
28119   31          4  221167         14             15               0   
...    ...        ...     ...        ...            ...             ...   
18915   31          6  186420         12             14               5   
1919    35          4  225330          9             13               4   
6336    42          2  117227         12             14               0   
7521    28          4  150309         11              9               2   
25782   35          4  454843         15             10               2   

       occupation  relationship  race  sex  capital-gain  capital-loss  \
22466           6             0     4    1             0             0   
1826           10             4     4    0         99999             0   
6377           14             0     2    1             0             0   
19643           4             0     4    1         15024             0   
28119          13             1     4    0             0             0   
...           ...           ...   ...  ...           ...           ...   
18915          13             1     4    0             0             0   
1919            1             1     4    0             0             0   
6336           10             4     4    0             0             0   
7521            7             0     0    1             0             0   
25782           3             0     4    1             0             0   

       hours-per-week  native-country  
22466              63              39  
1826               40               6  
6377               40              39  
19643              65              39  
28119              35              39  
...               ...             ...  
18915              25              39  
1919               40              39  
6336               45              39  
7521               45              39  
25782              40              39  

[9769 rows x 14 columns]

In [34]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)
X_train_scaled

array([[-0.04042738,  0.08542558, -0.71032941, ..., -0.21676703,
         0.28971372,  0.28913545],
       [-0.48024645,  0.08542558, -0.36165646, ..., -0.21676703,
        -0.03317106,  0.28913545],
       [-1.50649094, -2.66460233, -0.09354588, ..., -0.21676703,
        -0.03317106,  0.28913545],
       ...,
       [-0.18703374,  0.08542558,  1.15805177, ..., -0.21676703,
        -0.03317106,  0.28913545],
       [-0.40694327, -1.97709535, -0.89785877, ..., -0.21676703,
        -0.03317106,  0.28913545],
       [-1.35988459,  0.08542558, -1.45992817, ..., -0.21676703,
         1.58125281,  0.28913545]])

In [35]:
X_test_scaled

array([[ 0.10617897,  0.08542558,  0.33750004, ..., -0.21676703,
         1.82341639,  0.28913545],
       [-1.21327823,  1.46043953,  0.12746075, ..., -0.21676703,
        -0.03317106, -3.93758862],
       [ 0.54599804,  0.08542558,  1.65509037, ..., -0.21676703,
        -0.03317106,  0.28913545],
       ...,
       [ 0.25278533, -1.28958837, -0.68064308, ..., -0.21676703,
         0.37043491,  0.28913545],
       [-0.77345916,  0.08542558, -0.36867255, ..., -0.21676703,
         0.37043491,  0.28913545],
       [-0.26033692,  0.08542558,  2.50315005, ..., -0.21676703,
        -0.03317106,  0.28913545]])

In [36]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression(random_state=0).fit(X_train_scaled,y_train)
log_reg.predict(X_train_scaled)

array([0, 0, 0, ..., 0, 0, 0], dtype=int8)

In [37]:
log_reg.score(X_train_scaled,y_train)

0.8264303264303264

In [38]:
log_reg.score(X_test_scaled,y_test)

0.8217831917289384

In [39]:
y_pred= log_reg.predict(X_test_scaled)
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test,y_pred)
cm

array([[6941,  381],
       [1360, 1087]], dtype=int64)

In [40]:
from sklearn.metrics import classification_report
report =classification_report(y_test,y_pred)
report

'              precision    recall  f1-score   support\n\n           0       0.84      0.95      0.89      7322\n           1       0.74      0.44      0.56      2447\n\n    accuracy                           0.82      9769\n   macro avg       0.79      0.70      0.72      9769\nweighted avg       0.81      0.82      0.81      9769\n'